name: Tosochu
main: amata1219.tosochu.Tosochu
version: 1.0.0
author: amata1219(Twitter@amata1219)

commands:
  start:
    aliases: g_start
  end:
    aliases: g_end
  worldtp:
  mapload:
  mapunload:
  mapmove:
  hrs:
   aliases: hsr
  msr: